### ISSUE TITLE
awaitOfferings not working on android

### ISSUE THREAD

**Issue by Moozart** [RevenueCat/purchases-kmp#198] opened 2024-09-12 19:58 UTC
Upgrade from kobankat (v0.4.0-7.9.0-4.41.0) to purchase-kmp(v1.0.0+13.2.0) awaitOfferings not working on android. IOS side works after migration but android does not shown offerings.

Log: 
D  Same call already in progress, adding to callbacks map with key: BackgroundAwareCallbackCacheKey(cacheKey=[/subscribers/****/offerings], appInBackground=false)

D  Request already scheduled with jitter delay, adding existing callbacks to unjittered request with key: ***

Where could the problem be?

**Comment by JayShortway** [comment] 2024-09-13 09:07
Hi, thanks for reporting! And thanks for being an early KobanKat user 😄 

I'm unfortunately unable to reproduce this problem on my end. Can you send a snippet of code showing how you're calling `awaitOfferings()`? Does the non-suspending `getOfferings()` work?

**Comment by JayShortway** [comment] 2024-09-16 07:54
Glad you were able to fix it! 

Just for my understanding, how were you using `CacheFetchPolicy`?

**Comment by JayShortway** [comment] 2024-09-23 09:18
Closing this, as the issue was reported fixed. Feel free to reopen if you have any more issues.

**Closed by JayShortway** 2024-09-23 09:18 UTC
Labels: bug
